version: '3.5'

services:
  lumen:
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: php -S lumen:80 -t public
    restart: always
    networks:
      - sail
    depends_on:
        - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - sail
    volumes:
      - dbdata:/var/lib/mysql
networks:
  sail:
    driver: bridge
volumes:
  dbdata:
    driver: local